### ISSUE TITLE
Error: 'XLMInterpreter' object has no attribute 'parse_cell_address'

### ISSUE THREAD

**Issue by rsaccani** [DissectMalware/XLMMacroDeobfuscator#62] opened 2020-11-23 10:36 UTC
By testing the attached sample, I get the following output:

```
Unencrypted xls file

[Loading Cells]
auto_open: auto_open->JsccwgbH!$B$138
[Starting Deobfuscation]
CELL:B162      , FullEvaluation      , http://SET.NAME("icWgeRooj",0)
CELL:B164      , FullEvaluation      , http://SET.NAME("dMblbtttKW",Sheet1$D$71:$D$109)
CELL:B168      , FullEvaluation      , http://SET.NAME("bdsUCc",$K$82:$K$91)
CELL:B171      , FullEvaluation      , http://SET.NAME("WBxfacTAO",179)
CELL:B173      , FullEvaluation      , http://SET.NAME("NmoxdYQdrueS",2)
Error: 'XLMInterpreter' object has no attribute 'parse_cell_address'
[END of Deobfuscation]
time elapsed: 0.08484935760498047
```

Sample:
[excel4weird.zip](https://github.com/DissectMalware/XLMMacroDeobfuscator/files/5582299/excel4weird.zip)

**Comment by DissectMalware** [comment] 2020-11-30 04:47
Please update from the master branch. The problem is now resolved in the latest commit.

pip install -U https://github.com/DissectMalware/xlrd2/archive/master.zip
pip install -U https://github.com/DissectMalware/pyxlsb2/archive/master.zip
pip install -U https://github.com/DissectMalware/XLMMacroDeobfuscator/archive/master.zip


![image](https://user-images.githubusercontent.com/9646319/100569829-38417400-329d-11eb-91a3-147ac4692869.png)

**Closed as completed** 2020-11-30 05:00 UTC
Labels: bug
